fastlane_version '2.63.0'
default_platform :ios

UNIT_TEST_SCHEME = 'Tests'
XC_PROJECT = 'ScrollViewController.xcodeproj'

platform :ios do

  desc 'Bootstrap project'
  lane :setup do
    puts 'Updating CocoaPods spec-repo'
    sh 'cd .. && bundle exec pod repo update'
    puts 'Bootstraping Carthage'
    sh 'cd .. && carthage bootstrap --platform iOS'
  end

  desc 'Run unit tests'
  lane :test do
    sh [
      'cd .. && set -o pipefail &&',
      'xcodebuild test',
      "-project #{XC_PROJECT}",
      "-scheme #{UNIT_TEST_SCHEME}",
      '-sdk iphonesimulator',
      '-destination \'platform=iOS Simulator,name=iPhone 8,OS=latest\'',
      'ONLY_ACTIVE_ARCH=YES',
      '| xcpretty -f `xcpretty-travis-formatter`'
    ].join(' ')
  end

  desc 'Lint pod'
  lane :pod_lint do
    sh 'cd .. && bundle exec pod lib lint'
  end

end
