fastlane_version '2.63.0'
default_platform :ios

UNIT_TEST_SCHEME = 'Tests'
XC_WORKSPACE = 'ScrollViewController.xcworkspace'

platform :ios do

  desc 'Bootstrap project'
  lane :setup do
    system 'diff ../Podfile.lock ../Pods/Manifest.lock > /dev/null'
    if $?.exitstatus != 0 then
      puts 'The sandbox is not in sync with the Podfile.lock, installing pods'
      sh 'cd .. && bundle exec pod install --repo-update'
    else
      puts 'Skipping pod install, the sandbox is in sync with the Podfile.lock'
    end

    puts 'Bootstraping Carthage'
    sh 'cd .. && carthage bootstrap'
  end

  desc 'Run unit tests'
  lane :test do
    sh [
      'cd .. && set -o pipefail &&',
      'xcodebuild test',
      "-workspace #{XC_WORKSPACE}",
      "-scheme #{UNIT_TEST_SCHEME}",
      '-sdk iphonesimulator',
      '-destination \'platform=iOS Simulator,name=iPhone 8,OS=latest\'',
      'ONLY_ACTIVE_ARCH=YES',
      '| xcpretty -f `xcpretty-travis-formatter`'
    ].join(' ')
  end

  desc 'Lint pod'
  lane :pod_lint do
    sh 'cd .. && bundle exec pod lib lint'
  end

end
