fastlane_version '2.63.0'
default_platform :ios

platform :ios do

  desc 'Bootstrap project'
  lane :setup do
    puts 'Updating CocoaPods spec-repo'
    sh 'cd .. && bundle exec pod repo update'
    puts 'Bootstraping Carthage'
    carthage(
      command: 'bootstrap',
      platform: 'iOS',
      use_binaries: false,
      cache_builds: true
    )
  end

  desc 'Run unit tests'
  lane :test do
    scan(
      project: 'ScrollViewController.xcodeproj',
      scheme: 'Tests',
      device: 'iPhone Xs'
    )
  end

  desc 'Generate test coverage report in HTML format'
  lane :coverage_html do
    slather(
      proj: 'ScrollViewController.xcodeproj',
      scheme: 'Tests',
      binary_basename: 'ScrollViewController',
      output_directory: 'coverage_report',
      use_bundle_exec: true,
      teamcity: true,
      html: true,
      verbose: true
    )
  end

  desc 'Lint pod'
  lane :pod_lint do
    sh 'cd .. && bundle exec pod lib lint --allow-warnings'
  end

  desc 'Deploy to CocoaPods'
  lane :pod_deploy do
    sh 'cd .. && bundle exec pod trunk push --allow-warnings'
  end

end
